"""
Shared data models (Pydantic).

The fields of these models are specified explicitly in the project subject
(Chapter V), so you do not need to design them yourselves. But you must
understand what each field is for, because the review will ask
"what is this field for?".
"""
from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


# --------------------------------------------------------------------------
# Sandbox configuration (Section V.2)
# --------------------------------------------------------------------------
class SandboxConfig(BaseModel):
    """Sandbox configuration for student solutions.

    Uses an allowlist strategy: only modules listed in authorized_imports
    can be imported, everything else is rejected.
    """

    authorized_imports: List[str] = Field(
        default_factory=lambda: [
            "math", "math.*",
            "collections", "collections.*",
            "itertools", "re", "json",
            "typing", "typing.*",
            "functools", "operator",
            "heapq", "bisect", "copy",
            "string", "random",
            "datetime", "datetime.*",
            "array", "cmath",
        ]
    )
    allowed_directories: List[str] = Field(
        default_factory=lambda: ["/testbed", "/tmp/agent"]
    )
    max_execution_time_seconds: int = 30
    max_memory_mb: int = 512


# --------------------------------------------------------------------------
# MBPP task input (Section V.3)
# --------------------------------------------------------------------------
class MBPPTaskInput(BaseModel):
    """Input for MBPP task evaluation."""

    task_id: int
    task_definition: str
    function_definition: str
    test_imports: List[str] = Field(default_factory=list)
    test_list: List[str] = Field(default_factory=list)


# --------------------------------------------------------------------------
# SWE-bench task input (Section V.4)
# --------------------------------------------------------------------------
class SWEBenchTaskInput(BaseModel):
    """Input for a SWE-bench task, provided by the moulinette.

    Your agent receives this and must produce a git patch that fixes the issue.
    """

    instance_id: str = Field(
        ..., description="SWE-bench instance identifier (e.g., 'sympy__sympy-23534')"
    )
    problem_statement: str = Field(
        ..., description="The GitHub issue description, what needs to be fixed"
    )
    docker_image: str = Field(
        ..., description="Full Docker image name to pull"
    )
    eval_script: str = Field(
        ..., description="Bash script to run inside the container to evaluate the patch"
    )
    hints_text: str = Field(default="", description="Optional hints about the issue")
    repo: str = Field(default="", description="Repository name (e.g., 'sympy/sympy')")


# --------------------------------------------------------------------------
# Record of each agent step (Section V.3 / V.4)
# --------------------------------------------------------------------------
class StepMetrics(BaseModel):
    """Metrics for a single agent step.

    Each step corresponds to one LLM generate -> sandbox execute cycle.
    """

    step: int = Field(..., description="1-indexed iteration number")
    input_tokens: int = Field(..., description="Tokens sent to the LLM for this step")
    output_tokens: int = Field(..., description="Tokens generated by the LLM for this step")
    request_time_ms: float = Field(..., description="Wall-clock time for the LLM API call (ms)")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    api_url: str = Field(default="", description="Base URL of the LLM API endpoint")
    model_name: str = Field(default="", description="Model identifier used for this step")
    llm_output: str = Field(default="", description="Raw text generated by the LLM")
    sandbox_input: str = Field(default="", description="Python code sent to the sandbox")
    sandbox_output: str = Field(default="", description="Sandbox execution result")
    retries: int = Field(default=0, description="Number of LLM API retries for this step")


# --------------------------------------------------------------------------
# Final agent output (the structure the evaluation uses for scoring,
# the format must not change)
# --------------------------------------------------------------------------
class SolutionOutput(BaseModel):
    """Output from student solution, required format for evaluation.

    This is the JSON structure your agent must produce and write to solution.json.
    """

    task_id: str = Field(..., description="MBPP task_id as string, or SWE-bench instance_id")
    benchmark: str = Field(..., description="'mbpp' or 'swebench'")
    success: bool = Field(..., description="Whether the agent believes it solved the task")
    solution: str = Field(..., description="For MBPP: the Python code. For SWE-bench: the git patch")
    iterations: int = Field(..., description="Number of agent loop iterations used")
    total_requests: int = Field(..., description="Total LLM API requests made (including retries)")
    total_input_tokens: int = Field(..., description="Sum of input_tokens across all steps")
    total_output_tokens: int = Field(..., description="Sum of output_tokens across all steps")
    total_time_seconds: float = Field(..., description="Wall-clock time from agent start to finish")
    steps: List[StepMetrics] = Field(default_factory=list)
    system_prompt: str = Field(default="", description="Full system prompt sent to the LLM")
    error: Optional[str] = Field(default=None, description="Error message if the agent failed")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
